name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USER: lvmi
      APP: archon
    steps:
      - name: Set docker tags
        id: set-tags
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]
          then
            echo ::set-output name=TAGS::$USER/$APP:latest
          elif [[ $GITHUB_REF == refs/heads/* ]]
          then
            BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/[\/]/_/g')
            echo ::set-output name=TAGS::$USER/$APP:$BRANCH
          else
            echo ::set-output name=TAGS::$USER/$APP:${GITHUB_REF#refs/tags/},$USER/$APP:latest
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.get-ref.outputs.TAGS }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
